### ISSUE TITLE
Embed URL for list of LaTeX symbols gives 404 error

### ISSUE THREAD

**Issue by Electw** [coffeebank/wyscdocs#1]
found in ` wyscdocs/cafe/texit/the-great-big-list-of-latex-symbols.md `
![image](https://user-images.githubusercontent.com/55963122/94174895-c129d280-fe4a-11ea-92ca-8d509fd8ef8a.png)

**Comment by coffeebank** [comment]
Thanks, I looked into this and found that Gitbook formats urls in its backend differently, so that the link as shown [on the GitHub file](https://github.com/coffeebank/wyscdocs/blob/master/cafe/texit/the-great-big-list-of-latex-symbols.md) won't work, but the link [on Gitbook being shown to the public](https://gdocs.gitbook.io/wysc/cafe/texit/the-great-big-list-of-latex-symbols) still works.

I should probably put a notice somewhere that Wysc Docs has moved from Gitbook to [our own website](https://wysc.us.to/docs) ([GitHub here](https://github.com/coffeebank/wysc/tree/master/docs/_docs))....
